### PR TITLE
Optimizations everywhere....

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
So, this PR looks huge, but only does a few things:
 - Update Gradle to 7.3.3
 - Optimize code (some things are faster now, others are just as fast as before)
 - Removed unnecessary casts and similar unnecessary stuff

### CODE REVIEW

**Comment by paulevsGitch** [comment]
Hi, after the latest PR Betaloader stopped working in dev environment. Looks like it is missing some libraries in gradle.build, but when I added them they are still missing. Do you know possible reason of it? I looked into STAPI sources and looks like this libraries are used before. I'm talking about "benjiman:expressions"

I tried to add this into gradle:
```
	implementation "blue.endless:jankson:1.2.1"
	implementation "com.github.jhalterman:typetools:87240d6"
	implementation "com.github.benjiman:expressions:7ed6748"
```

**Comment by ThexXTURBOXx** [comment]
Give me a second, I am gonna investigate this

**Comment by ThexXTURBOXx** [comment]
See #4 :)

**Comment by paulevsGitch** [comment]
Thank you, now it works fine =)

**Comment by ThexXTURBOXx** [comment]
No problem! Sorry for breaking your environment first 😅

**Pull request merged**
